### ISSUE TITLE
Hashlist handling broken when usernames contain spaces

### ISSUE THREAD

**Issue by fransla** [lachlan2k/phatcrack#25]
For NetNTLMv2 hashes in particular (where the username forms part of the seed), it is important to be able to handle the parsing of hashes where the usernames contain spaces.

(For other types some preprocessing can overcome this issue).

Creating such a hashlist fails with error 400 (type 5600).

**Comment by lachlan2k** [comment]
Looks like a stupid UI bug that's causing the list of hashes to be tokenized by any whitespace rather than newlines.

Should be fixed now in commit 10866334d6725f21bec78141474bc952be50d999

I've also migrated the frontend error handling for this functionality to the newer stuff that should show more useful errors in the toasts.

This commit will make it into a release once we get your other issue sorted out
