### ISSUE TITLE
Hashlist ordering getting shuffled

### ISSUE THREAD

**Issue by JSmith-Aura** [lachlan2k/phatcrack#42]
Each time that `api/v1/hashlist/<hashlist_id>` is queried the frontend hashlist shuffles to a new random ordering which is quite distracting when a job is running. 

```go
func GetHashlistWithHashes(hashlistId string) (*Hashlist, error) {
	var hashlist Hashlist
	err := GetInstance().Preload("Hashes").First(&hashlist, "id = ?", hashlistId).Error
	if err != nil {
		return nil, err
	}
	return &hashlist, nil
}
```

I believe this is happening because the Preload doesnt have an order specified, e.g:
```go
err := db.Where("id = ?", userID).Preload("Schools")
.Preload("Schools.Jobs", func(db *gorm.DB) *gorm.DB {
    return db.Order("job.job_reference DESC")
}).Scan(&user).Error
return &user.Schools, err
```

**Comment by lachlan2k** [comment]
As discussed, this only happens when a new cracked hash has been added to the list. Only becomes distracting on very very large sets of hashes where the results are coming in quite quickly.

The solution would be to sort the DB query, first in terms of if its cracked, second in terms of ID. However, I'd need to performance test this for sets of hashes (i.e. 10k+) to evaluate any perf concerns, and I can't be bothered doing that quite yet. Might revisit in future
