### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by kiriknik** [lachlan2k/phatcrack#48]
Try to start server part, always get error from ssl
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

Starts as https://github.com/lachlan2k/phatcrack?tab=readme-ov-file#deployment

**Comment by kiriknik** [comment]
Sorry, i think your container already have default ssl certs)
Can you provide additional info in README? Like "if you want a self signed certswith caddy - run next
docker run -v $(pwd)/:/certs stakater/ssl-certs-generator:1.0"

**Comment by lachlan2k** [comment]
The README already includes instructions on how to use self-signed certs:


```
## Otherwise, use the following for self-signed TLS
# echo "TLS_OPTS=tls internal" >> .env
```

Although it is easy to miss because it's greyed out by the code block syntax highlighting.

Soon, there will be a guided install script that interactively prompts the user for what TLS configuration they would like. There will also be an official docs site soon, and the manual installation documentation will have a highlight to call attention to correctly setting the TLS_OPTS variable.
